# Generated by Django 4.2.7 on 2023-12-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='thumbnail',
            field=models.ImageField(default='events/thumbnails/default.png', upload_to='events/thumbnails'),
        ),
    ]
