# Generated by Django 4.2.7 on 2023-12-24 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_referral_code'),
        ('events', '0002_event_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='latest_update',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('course', models.CharField(choices=[('B.Tech', 'B.Tech'), ('BCA', 'BCA'), ('BBA', 'BBA'), ('MBA', 'MBA'), ('BA', 'BA')], default='B.Tech', max_length=20)),
                ('year', models.CharField(choices=[('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year'), ('4th Year', '4th Year')], default='1st Year', max_length=20)),
                ('hosteller_dayScholar', models.CharField(choices=[('Day Scholar', 'Day Scholar'), ('Hosteller', 'Hosteller')], default='Day Scholar', max_length=20)),
                ('referral_code', models.CharField(blank=True, max_length=20, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('member_referral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
    ]
