# Generated by Django 4.2.7 on 2023-12-24 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_latest_update_registration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='member_referral',
            new_name='referral_name',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='referral_code',
        ),
    ]
