# Generated by Django 4.2.7 on 2023-12-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_rename_member_referral_registration_referral_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='referral_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
