# Generated by Django 4.2.7 on 2023-12-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_registration_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='events/payment_screenshots'),
        ),
        migrations.AddField(
            model_name='registration',
            name='referrance_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
