# Generated by Django 4.2.7 on 2023-12-25 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_registration_payment_screenshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='email',
            field=models.EmailField(default='divyanshu.khandelwal_cs.aiml21@gla.ac.in', max_length=254),
            preserve_default=False,
        ),
    ]
