# Generated by Django 4.2.7 on 2023-12-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_registration_approved_by_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='is_present',
            field=models.BooleanField(default=False),
        ),
    ]
