# Generated by Django 4.2.7 on 2023-12-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_event_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='other_referral_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
