# Generated by Django 4.2.7 on 2023-12-30 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_registration_other_referral_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='registration_type',
            field=models.CharField(blank=True, choices=[('Solo', 'Solo'), ('Group', 'Group'), ('Duo', 'Duo')], default='Solo', max_length=20, null=True),
        ),
    ]
