# Generated by Django 4.2.7 on 2023-12-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_registration_registration_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='duo_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='group_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='solo_price',
            field=models.IntegerField(default=0),
        ),
    ]
