# Generated by Django 4.2.7 on 2023-12-31 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_event_duo_price_event_group_price_event_solo_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_solo',
            field=models.BooleanField(default=False),
        ),
    ]
