# Generated by Django 4.2.7 on 2023-12-31 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_event_is_solo'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='mode_of_payment',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Online', 'Online')], max_length=20, null=True),
        ),
    ]
