# Generated by Django 4.2.7 on 2024-01-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_registration_mode_of_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='mobile_number',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
