# Generated by Django 4.2.7 on 2024-01-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_registration_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.CharField(default='', max_length=200),
        ),
    ]
