# Generated by Django 4.2.7 on 2023-12-23 17:34

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('course', models.CharField(choices=[('B.Tech', 'B.Tech'), ('BCA', 'BCA'), ('BBA', 'BBA'), ('MBA', 'MBA'), ('BA', 'BA')], default='B.Tech', max_length=20)),
                ('year', models.CharField(choices=[('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year'), ('4th Year', '4th Year')], default='1st Year', max_length=20)),
                ('team', models.CharField(choices=[('Technical Team', 'Technical Team'), ('Event Management Team', 'Event Management Team'), ('Corporate Relations (CR) Team', 'Corporate Relations (CR) Team'), ('Creative Team', 'Creative Team'), ('Data Team', 'Data Team'), ('Design Team', 'Design Team'), ('Editoral Team', 'Editoral Team'), ('Finance Team', 'Finance Team'), ('Public Relations (PR) Team', 'Public Relations (PR) Team')], default='Technical Team', max_length=50)),
                ('post', models.CharField(choices=[('President', 'President'), ('Vice President', 'Vice President'), ('General Secretary', 'General Secretary'), ('Joint Secretary', 'Joint Secretary'), ('Treasurer', 'Treasurer'), ('Curator', 'Curator'), ('Head', 'Head'), ('Deputy Head', 'Deputy Head'), ('Associate', 'Associate'), ('Member', 'Member')], default='Member', max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10)),
                ('mobile_number', models.IntegerField(max_length=10)),
                ('profile_pic', models.FileField(upload_to='images')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
