# Generated by Django 4.2.7 on 2023-12-26 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_member',
            field=models.BooleanField(default=False),
        ),
    ]
