# Generated by Django 4.2.7 on 2023-12-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_rename_payment_ss_profile_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='qr_code',
            field=models.ImageField(blank=True, default='/images/default.png', null=True, upload_to='images/'),
        ),
    ]
